server:
  port: 8080
  max-http-header-size: 8KB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_proxy?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root